C      PROGRAM TO CALCULATE THE AREA AND THE PERIMETER OF SQUARE
       WRITE(*,*)'ENTER THE ARM OF SQUARE'
       READ(*,*)A
       AREA=A**2
       PERIMETER=4*A
       WRITE(*,*)'RESULT IS ',AREA, PERIMETER
       STOP
       END
