        WRITE(*,*)'MARKS OF THREE SUB.MI,M2,M3'
        PERSENTAGE=(M1+M2+M3/300)*100
        "IF (P.GT.60PER)THEN PERFORM STEP 4 OTHERWISE PERFORM STEP 5"
        WRITE(*,*)'FIRST DIVESION'
        "IF (P.GT.45PER)THEN PERFORM STEP 6 OTHERWISE PERFORM STEP 7"
        WRITE(*,*)'SECOND DIVESION'
        WRITE(*,*)'THEIRD DIVESION'
        
        STOP
        END



       















