C     PROGRAME TO CALCULATE THE AREA AND CIRCUMFRENCE OF A CIRCLE
      WRITE(*,*)'ENTER THE SIZE OF RADIUS'
      READ(*,*)R
      CIRCUMFRENCE=2*3.14*R
      AREA=(3.14*R)**2
      WRITE(*,*)'RESULT IS', CIRCUMFRENCE ,AREA
      STOP
      END
