c       program to find series1,3,6,10...
c       program developed by JETENDER on 11/10/07
        
        WRITE(*,*)'how many number'
        READ(*,*)n
        i=0
        j=1
12      if(i.LE.(n)) THEN
        I=I+J
        WRITE(*,*)I
        J=J+1
        GO TO12
        ENDIF
        STOP
        END





                        series




how many number
12
            1
            3
            6
           10
           15
Stop - Program terminated.

