
LACHOO    FORTRAN77 V4.21 August 1988
(C) Copyright Microsoft Corp LACHOO COLLEGE        

Line invalid: ';', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Line invalid: '', start again.
Source filename [.FOR]: Object filename [SD.OBJ]: Source listing  [NUL.LST]: Object listing  [NUL.COD]: File access error in file SD.FOR, error code 1032
