C     PROGRAM TO CALCULATE SIMPLE INTEREST
      WRITE(*,*)'ENTER THE PRINCIPLE'
      READ(*,*)P
      WRITE(*,*)'ENTER THE RATE'
      READ(*,*)R
      WRITE(*,*)'ENTER THE TIME'
      READ(*,*)T
      SI=P*R*T/100
      WRITE(*,*)'THE SIMPLE INTEREST IS',SI
      WRITE(*,*)'CREATED BY RADHE SHYAM JANGID'
      STOP
      END
